language: node_js
cache:
  directories:
  - node_modules
node_js:
- node
- '10'
branches:
  only:
  - master
jobs:
  include:
  - stage: npm release
    script:
    - npm run build
deploy:
  edge: true
  cleanup: true
  provider: npm
  email:
    secure: bIgN0XxkuO9xNUsGktFzhwtMU2G6cpQOLyCB/DbMn1qR4YuytAAeAFShzud9DS2juKGKlXbCyjiz5G1nlf3KH9AHPigcQ1maMtDyWY5o+8JJFa1DEKqf+aVwck5Yypn8OrbtFGkhlIW84z26ThiYY6pj9J8ogRipxtK7gvWmSxqFpUnq1Flu+Vhn8Uet6oXbwJPY7BSp1JaPUmXBvcbKgKX9Plyb+YQJXkZ8crJTowjKCDJm/AmZP9FywT5jYl/NcqqW4ptSPxOA3QvTKrCntuuE+KW33qm8JE3Aw5twN1O3H2xzQkEdUGdbzXcIhrWwekqM+lCQS5dcdB+wqWP8/7+/IQmkrVrkOvLTEFuJXhdCVaoRy4jwIjeCSVP+u7PpVl/BJP9TrFkiQ98dk/UN4cKT9JyrzON+LhjdrCs4QAw9MYTKJlRjKL9bn2oF2aOfuTpXHWAL3hHau59m8QVr4ySixqm5nUQ2xXS+qikBp+3ldzACVxz9iCrHutqSMe0wqTcmkRFEi02sJ2zXgAy4oIzuA6hCScOgswBy8Ph22gpID8Eq7DdhMU2qPj/aZfdg+aL7hTp9Lg5QnAMrFhlBsXvAkIQxNWwRDcA5xYq6JtwgqKnrAgIgR7Ir5o9efn1o0FifGchouL0W8EJ7xXHbw4unt98Qs2jnGpNPuXVtzME=
  api_key:
    secure: n2O4vimDZBI2jueO0rd3F4jfT0h1uF6wkexJb2TsWtRmQ+1YW67JLs6bTZnMcuODxuhLxibSbwrWo9j5U2jO0V0Unr90KWnyufwtSbGni+K4137k/K8wfo/PlPD+QNxB0zmWCYF6AjFpERcrnQSDHk8t7W+UmiHXWhNJncwaElS4sEK0O7PiO0WxOcJ7fpQjbtPZYrmvCzhDdBC9RfS0gRRx9hysPb/vBDmwS5U8ftmITJjGRi35WJ+Ep2Vz0p+cGu0ljnPp+l/ajleexc6T8L6I+CTifdK5s7CsGXnF//NEfzh76H48s8QGieIdWG+1MFs9NrKE8IrSRi8F/di9p8v7VJN3tEqyho6p62VEt1bLfyPHoK/Sz/hvEgXJocTiiHaM91lTTwnBpE4iJ+s1lZg7mAfVEkTgHCiBbQogELiRw4oQNmRFWSJt4NSaprjBvw6P959edybO50vQRdGUikxz0deaeo2vyi8WPhFPR37HySTpHF/y3wJ2Spwn+IfVyVqFCkWxE+tA8MrF9SISF1ciUOEr3b0OTOcUWuGAcpZu5KAOX3S4Fnyn3Vs7AlT6Lbyy+H8a9s7e394+N08Bu+qWlBtVcm90BO0tiYFfp6iDzHupg9L91d9E8XDJ4/dYJmFjuO0Mjo0XARIjpUJzEzevL3jYo9sabN7KOPdx5Zo=
